CREATE OR ALTER PROCEDURE AddProduct
	@Name	nvarchar(max),
	@Sku	nvarchar(max),
	@Price	decimal,
	@Weight	decimal,
	@Length	decimal,
	@Width	decimal,
	@Height	decimal,
	@CreatedOnUtc	datetime2,
	@CategoryId	int,
	@StockQuantity int,
	@ProductCode nvarchar(400),
	@ProductId int OUTPUT
AS
	INSERT INTO PRODUCT(
						ProductTypeId,
						ParentGroupedProductId,
						VisibleIndividually,
						Name,
						ShortDescription,
						FullDescription,
						AdminComment,
						ProductTemplateId,
						VendorId,
						ShowOnHomepage,
						MetaKeywords,
						MetaDescription,
						MetaTitle,
						AllowCustomerReviews,
						ApprovedRatingSum,
						NotApprovedRatingSum,
						ApprovedTotalReviews,
						NotApprovedTotalReviews,
						SubjectToAcl,
						LimitedToStores,
						Sku,
						ManufacturerPartNumber,
						Gtin,
						IsGiftCard,
						GiftCardTypeId,
						RequireOtherProducts,
						RequiredProductIds,
						AutomaticallyAddRequiredProducts,
						IsDownload,
						DownloadId,
						UnlimitedDownloads,
						MaxNumberOfDownloads,
						DownloadExpirationDays,
						DownloadActivationTypeId,
						HasSampleDownload,
						SampleDownloadId,
						HasUserAgreement,
						UserAgreementText,
						IsRecurring,
						RecurringCycleLength,
						RecurringCyclePeriodId,
						RecurringTotalCycles,
						IsRental,
						RentalPriceLength,
						RentalPricePeriodId,
						IsShipEnabled,
						IsFreeShipping,
						ShipSeparately,
						AdditionalShippingCharge,
						DeliveryDateId,
						IsTaxExempt,
						TaxCategoryId,
						IsTelecommunicationsOrBroadcastingOrElectronicServices,
						ManageInventoryMethodId,
						UseMultipleWarehouses,
						WarehouseId,
						StockQuantity,
						DisplayStockAvailability,
						DisplayStockQuantity,
						MinStockQuantity,
						LowStockActivityId,
						NotifyAdminForQuantityBelow,
						BackorderModeId,
						AllowBackInStockSubscriptions,
						OrderMinimumQuantity,
						OrderMaximumQuantity,
						AllowedQuantities,
						AllowAddingOnlyExistingAttributeCombinations,
						DisableBuyButton,
						DisableWishlistButton,
						AvailableForPreOrder,
						PreOrderAvailabilityStartDateTimeUtc,
						CallForPrice,
						Price,
						OldPrice,
						ProductCost,
						CustomerEntersPrice,
						MinimumCustomerEnteredPrice,
						MaximumCustomerEnteredPrice,
						BasepriceEnabled,
						BasepriceAmount,
						BasepriceUnitId,
						BasepriceBaseAmount,
						BasepriceBaseUnitId,
						HasTierPrices,
						HasDiscountsApplied,
						Weight,
						Length,
						Width,
						Height,
						AvailableStartDateTimeUtc,
						AvailableEndDateTimeUtc,
						DisplayOrder,
						Published,
						Deleted,
						CreatedOnUtc,
						UpdatedOnUtc,
						OverriddenGiftCardAmount,
						MarkAsNew,
						MarkAsNewStartDateTimeUtc,
						MarkAsNewEndDateTimeUtc,
						NotReturnable,
						ProductAvailabilityRangeId,
						NameChanged,
						IsScrapedProduct
						) VALUES (
							5,
							0,
							'True',
							@Name,
							null,
							null,
							null,
							1,
							0,
							'False',
							null,
							null,
							null,
							'True',
							0,
							0,
							0,
							0,
							'True',
							'False',
							@Sku,
							@ProductCode,
							null,
							'False',
							0,
							'False',
							null,
							'False',
							'False',
							0,
							'True',
							10,
							null,
							0,
							'False',
							0,
							'False',
							null,
							'False',
							100,
							0,
							10,
							'False',
							1,
							0,
							'True',
							'False',
							'False',
							0,
							0,
							'False',
							0,
							'False',
							0,
							'False',
							0,
							@StockQuantity,
							'False',
							'False',
							0,
							0,
							1,
							0,
							'False',
							1,
							10000,
							null,	
							'False',	
							'False',
							'False',
							'False',
							null,	
							'False',
							@Price,	
							0,	
							0,
							'False',
							0,
							1000,
							'False',
							0,
							1,
							0,
							1,
							'False',	
							'False',
							@Weight,	
							@Length,	
							@Width,	
							@Height,	
							null,	
							null,	
							0,	
							'True',	
							'False',	
							@CreatedOnUtc,	
							@CreatedOnUtc,	
							null,	
							'False',	
							null,	
							null,	
							'False',	
							0,
							'False',
							'True'
						);

		SET @ProductId = SCOPE_IDENTITY();
		DECLARE @Slug nvarchar(max) = REPLACE(LOWER(@Name),' ','-');

		INSERT INTO UrlRecord(EntityId, EntityName, Slug, IsActive, LanguageId) VALUES (@ProductId, 'Product', @Slug, 'True', 0);

		INSERT INTO Product_Category_Mapping(ProductId, CategoryId, IsFeaturedProduct, DisplayOrder) 
												VALUES (@ProductId, @CategoryId, 'False', 1);

		INSERT INTO AclRecord (EntityId, EntityName, CustomerRoleId)
						VALUES (@ProductId, 'Product', 6);

		RETURN @ProductId;